apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash-app
  template:
    metadata:
      labels:
        app: dash-app
    spec:
      containers:
      - name: dash-app
        image: us.icr.io/pratt_app/dash_app